dir    = File.dirname(__FILE__)  
to_file = true

task :load do
  require "#{dir}/lib/itinerary"
  FileList["#{dir}/days/*.rb"].each { |filename| require filename }  
end

desc 'modifier to send output to screen rather than file'
task :to_screen do
  to_file = false
end

desc 'generate the output in text format'
task :text => :load do
  if to_file
    mkdir_p "#{dir}/output/text" 
    File.open "#{dir}/output/text/itinerary.txt" , 'w' do |f|
      f.puts Itinerary.to_text
    end
  else
    puts Itinerary.to_text
  end
end

namespace :html do

  desc 'generate the output in simple html format'
  task :simple => :load do
    if to_file
      mkdir_p "#{dir}/output/html"
      cp_r    "#{dir}/data/itinerary/html/simple/public" , "#{dir}/output/simple_html"
      File.open "#{dir}/output/simple_html/itinerary.html" , 'w' do |f|
        Itinerary.to_simple_html(f)
      end
    else
      puts Itinerary.to_simple_html($stdout)
    end
  end

end

task :default => [ :text , 'html:simple' ]