dir    = File.dirname(__FILE__)  
to_file = true

task :load do
  require "#{dir}/lib/itinerary"
  FileList["#{dir}/days/*.rb"].each { |filename| require filename }  
end

desc 'modifier to send output to screen rather than file'
task :to_screen do
  to_file = false
end

desc 'generate the output in text format'
task :text => :load do
  if to_file
    mkdir_p "#{dir}/output/text" 
    File.open "#{dir}/output/text/itinerary.txt" , 'w' do |f|
      f.puts Itinerary.to_text
    end
  else
    puts Itinerary.to_text
  end
end

desc 'generate the output in html format'
task :html => :load do
  if to_file
    mkdir_p "#{dir}/output/html"
    File.open "#{dir}/output/html/itinerary.html" , 'w' do |f|
      f.puts Itinerary.to_html
    end
  else
    puts Itinerary.to_html
  end
end

task :default => [ :text , :html ]