task :default do
  file = File.dirname(__FILE__)
  require "#{file}/lib/itinerary"
  FileList["#{file}/days/*.rb"].each { |filename| require filename }
  mkdir_p "#{file}/output"
  File.open "#{file}/output/itinerary.txt" , 'w' do |f|
    f.puts Itinerary.to(:text)
  end
  
  # puts Itinerary.to :html
end