require 'project_euler/core_extensions/fixnum'
require 'project_euler/core_extensions/integer'
require 'project_euler/core_extensions/array'
require 'project_euler/core_extensions/enumerable'
require 'project_euler/fibs'
require 'project_euler/primes'
require 'project_euler/triangle_numbers'
require 'project_euler/pythagorean_triples'