(princ "               DIAMONDS")
(fresh-line)
(princ "For a pretty diamond pattern,")

(labels ((prompt ()
           (fresh-line)
           (princ "type in an odd number between 5 and 21: ")
           (let ((input (read)))
             (if (and (numberp  input   )
                      (integerp input   )
                      (oddp     input   )
                      (>=       input  5)
                      (<=       input 21))
                 input
                 (progn (princ "Invalid input.")
                        (fresh-line)
                        (prompt))))))
  (let* ((width (prompt))
         (half  (/ (1+ width) 2)))
    (loop for y-diamond from 1 to (/ 60 width)
          do (loop for y from 1 to width
                   do (fresh-line)
                      (loop for x-diamond from 1 to (/ 60 width)
                            do (loop for x from 1 to width
                                     do (let* ((offset      (if (<= y half)
                                                                (- y 1)    
                                                                (- width y)))
                                               (lower-bound (- half offset))
                                               (upper-bound (+ half offset))
                                               (mark?       (and (>= x lower-bound)
                                                                 (<= x upper-bound))))
                                           (princ (if mark? "X" " ")))))))))